### ISSUE TITLE
How to compile to 32 bit?

### ISSUE THREAD

**Issue by raelgc** [QupZilla/qtwebkit-plugins#2]
I'm building a Ubuntu package, and the compiled `.so` file appears to be `64bit` only.

Is there a way to build a `32bit` file?

**Comment by brcontainer** [comment]
@raelgc  Try added in your project `-m32`, like this:

```
QMAKE_CXXFLAGS += -m32
```

**Comment by raelgc** [comment]
I've tried that and several other options, like [this](http://qt-project.org/forums/viewthread/3719), but didn't work.

**Comment by nowrep** [comment]
If you are running 64bit system, you need to cross-compile for 32bit.

**Comment by raelgc** [comment]
Ok, I just installed a 32bit VM and compiled it.
