### ISSUE TITLE
Get suggestions in my application

### ISSUE THREAD

**Issue by brcontainer** [QupZilla/qtwebkit-plugins#5]
It is possible to get suggestions list from `Speller` when you right-click the text field, so I can create the "event to correct"?

At the time when I right-click a word misspelled show default `QMenu` (not shown suggestions), I believe that is why I must redeploy the menu. How to do this?

The current `QMenu` shows this:

![spellcheck](https://cloud.githubusercontent.com/assets/4368952/6549917/d3d26a02-c5fa-11e4-8eae-424c9e0b4422.png)

Thanks for the amazing code.

**Comment by nowrep** [comment]
Yes, you can take a look at QupZilla code: https://github.com/QupZilla/qupzilla/blob/v1.8/src/lib/webkit/webview.cpp#L870

**Comment by brcontainer** [comment]
@nowrep Got it, I liked the way you created the plugins in QupZilla you created your own box (I had not previously understood). Congratulations, it's very creative. An off-topic doubt, you want to move the Qupzilla project to qtwebengine?

Thanks again!

**Comment by JHooverman** [comment]
@brcontainer: for qtwebengine support in QupZilla you might want to look [here](https://github.com/QupZilla/qupzilla/wiki/FAQ#13-does-qupzilla-support-the-blink-web-rendering-engine-used-in-chromium).

**Comment by brcontainer** [comment]
@JHooverman Nice!
