### ISSUE TITLE
On KDE5, enabling DBus causes freeze after switching window focus from other application to QupZilla

### ISSUE THREAD

**Issue by Mikiya** [QupZilla/qtwebkit-plugins#9]
Without DBus support, everything works smoothly. However, once DBus support is enabled, short freeze is caused when switching focus from other application (e.g. Konsole) to QupZilla. I'm using QupZilla on KDE Plasma 5.8/Gentoo Linux.

**Comment by nowrep** [comment]
This plugin is not used in QupZilla, so this is irrelevant.
